# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9b7424c4053f9752ceff128903e0d131944e4cbfd64d2539302f18be9a590333bb8ec3a277a4ea77ff059b28caee07488f1ceee554907f198a8dc29e0c005d

test:
  secret_key_base: 53360226988253b5e1d59e9d3d247da136c9f3e5554db52ddeb3011c92c3320b7701ec2109f80164f1a1f17d97ef133c97277473c0ba087f6877a395339d9efa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
